version: 0.2

env:
 
  parameter-store:
      DOCKER_REGISTRY_USERNAME: /chiefbuilder/docker-credentials/username
      DOCKER_REGISTRY_PASSWORD: /chiefbuilder/docker-credentials/password
      DOCKER_REGISTRY_URL: /chiefbuilder/docker-credentials/registry_url

phases:
  install:
    runtime-versions:
       python: 3.9
  pre_build:
    commands:
       - pip install -r requirements.txt
     
  build:
    commands:
       - echo " Building Docker Image"
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
       
       - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
       - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
  post_build:
    commands:
       - echo "Docker Image have been built"
     
Ogbuchi Arinze